// <copyright file="StaffAvailability.cs" company="">
// Copyright (c) 2025 All Rights Reserved
// </copyright>
// <author></author>
// <date>6/17/2025 6:25:19 PM</date>
// <summary>Implements the StaffAvailability Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text.Json;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace EY.WorkforceAccelerator.Plugins
{

    /// <summary>
    /// StaffAvailability Plugin.
    /// </summary>    
    public class StaffAvailability: PluginBase
    {

        public StaffAvailability(string unsecure, string secure): base(typeof(StaffAvailability))
        {
            
           // TODO: Implement your custom configuration handling.
        }



        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
                throw new InvalidPluginExecutionException(nameof(localContext));
            ITracingService tracingService = localContext.TracingService;
            IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;
            IOrganizationService service = localContext.CurrentUserService;

            try
            {

                    try
                    {
                        tracingService.Trace("Plugin execution started.");

                        DateTime date = DateTime.Now;
                        if (context.InputParameters.Contains("WeekDate") && context.InputParameters["WeekDate"] is DateTime)
                        {
                            date = (DateTime)context.InputParameters["WeekDate"];
                            tracingService.Trace("Retrieved input parameter 'TaskSubject': " + date);
                    }


                    var queryDate = DateTime.Today;

                    // Get the week start date
                    var weekStartDate = GetWeekStart(date);
                    tracingService.Trace($"Processing week starting: {weekStartDate:yyyy-MM-dd}");

                    // Generate schedules for the week
                    var weeklySchedule = GenerateWeeklySchedule(weekStartDate, localContext);

                    var result = JsonSerializer.Serialize(weeklySchedule, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                        WriteIndented = true
                    });



                    context.OutputParameters["StaffAvailabilityResult"] = result;

                    }
                    catch (Exception ex)
                    {
                        tracingService.Trace("An error occurred: {0}", ex.ToString());
                        throw new InvalidPluginExecutionException($"An error occurred in the CreateWelcomeTaskAction plugin. message: {ex.Message}", ex);
                    }

                }
                catch (Exception ex)
                {
                    tracingService?.Trace("An error occurred executing Plugin EY.WorkforceAccelerator.Plugins.StaffAvailability : {0}", ex.ToString());
                    throw new InvalidPluginExecutionException($"Excpetion: {ex.Message} ", ex);
                }
        }



        private List<object> GenerateWeeklySchedule(DateTime weekStartDate, ILocalPluginContext localContext)
        {
            ITracingService tracingService = localContext.TracingService;
            IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;
            IOrganizationService service = localContext.CurrentUserService;

            tracingService.Trace($"Generating weekly schedule starting {weekStartDate:yyyy-MM-dd}");

            var weekEndDate = weekStartDate.AddDays(6);
            var weeklyAvailability = new List<object>();

            // Query pr_staffschedule for the given week
            var query = new QueryExpression("pr_staffschedule")
            {
                ColumnSet = new ColumnSet("pr_effectivedate", "pr_starttime", "pr_endtime"),
                Criteria = new FilterExpression(LogicalOperator.And)
            };

            // Filter for records within the week
            query.Criteria.AddCondition("pr_effectivedate", ConditionOperator.GreaterEqual, weekStartDate);
            query.Criteria.AddCondition("pr_effectivedate", ConditionOperator.LessEqual, weekEndDate);

            var scheduleRecords = service.RetrieveMultiple(query);
            tracingService.Trace($"Found {scheduleRecords.Entities.Count} schedule records for the week");

            // Group records by date and merge overlapping time slots
            var recordsByDate = scheduleRecords.Entities
                .GroupBy(r => r.GetAttributeValue<DateTime>("pr_effectivedate").Date)
                .ToList();

            foreach (var dateGroup in recordsByDate)
            {
                var currentDate = dateGroup.Key;
                var dayAvailability = ProcessDaySchedule(dateGroup.ToList(), currentDate, localContext);
                weeklyAvailability.AddRange(dayAvailability);
            }

            return weeklyAvailability;
        }

        private List<object> ProcessDaySchedule(List<Entity> scheduleRecords, DateTime date, ILocalPluginContext localPluginContext)
        {
            var dayAvailability = new List<object>();
            var timeSlots = new List<TimeSlot>();

            localPluginContext.Trace($"Processing {scheduleRecords.Count} records for {date:yyyy-MM-dd}");

            // Extract time slots from schedule records
            foreach (var record in scheduleRecords)
            {
                var startDateTime = record.GetAttributeValue<DateTime?>("pr_starttime");
                var endDateTime = record.GetAttributeValue<DateTime?>("pr_endtime");

                if (startDateTime.HasValue && endDateTime.HasValue)
                {
                    var startTime = startDateTime.Value.TimeOfDay;
                    var endTime = endDateTime.Value.TimeOfDay;

                    if (startTime < endTime)
                    {
                        timeSlots.Add(new TimeSlot
                        {
                            StartTime = startTime,
                            EndTime = endTime,
                            Date = date
                        });
                    }
                }
            }

            // Merge overlapping time slots
            var mergedSlots = MergeOverlappingTimeSlots(timeSlots);
            localPluginContext.Trace($"Merged {timeSlots.Count} slots into {mergedSlots.Count} non-overlapping slots for {date:yyyy-MM-dd}");


            // Convert merged slots to virtual entity records

            for (int i = 0; i < mergedSlots.Count; i++)
            {
                var slot = mergedSlots[i];
                var baseDate = DateTime.Today;
                var startDateTime = baseDate.Add(slot.StartTime);
                var endDateTime = baseDate.Add(slot.EndTime);

                var virtualEntity = new
                {
                    pr_starttime = startDateTime,
                    pr_endtime = endDateTime,
                    pr_effectivedate = slot.Date.ToString("yyyy-MM-dd")
                };

                dayAvailability.Add(virtualEntity);
            }


            return dayAvailability;
        }

        private List<TimeSlot> MergeOverlappingTimeSlots(List<TimeSlot> timeSlots)
        {
            if (!timeSlots.Any()) return new List<TimeSlot>();

            // Sort by start time
            var sortedSlots = timeSlots.OrderBy(ts => ts.StartTime).ToList();
            var mergedSlots = new List<TimeSlot>();

            var currentSlot = sortedSlots.First();

            for (int i = 1; i < sortedSlots.Count; i++)
            {
                var nextSlot = sortedSlots[i];

                // Check if slots overlap or are adjacent
                if (nextSlot.StartTime <= currentSlot.EndTime)
                {
                    // Merge slots - extend end time if necessary
                    currentSlot.EndTime = new TimeSpan(Math.Max(currentSlot.EndTime.Ticks, nextSlot.EndTime.Ticks));
                }
                else
                {
                    // No overlap, add current slot and start new one
                    mergedSlots.Add(currentSlot);
                    currentSlot = nextSlot;
                }
            }

            // Add the last slot
            mergedSlots.Add(currentSlot);

            return mergedSlots;
        }

        private TimeSpan? ParseTimeString(string timeString)
        {
            if (string.IsNullOrEmpty(timeString))
                return null;

            if (TimeSpan.TryParse(timeString, out TimeSpan result))
                return result;

            var formats = new[] { "HH:mm", "H:mm", "HH:mm:ss", "H:mm:ss" };
            foreach (var format in formats)
            {
                if (DateTime.TryParseExact(timeString, format, null, System.Globalization.DateTimeStyles.None, out DateTime dateTime))
                {
                    return dateTime.TimeOfDay;
                }
            }

            return null;
        }

        private DateTime? ExtractDateFromQueryExpression(FilterExpression filter, ILocalPluginContext localPluginContext)
        {
            if (filter?.Conditions == null) return null;

            foreach (var condition in filter.Conditions)
            {
                if (condition.AttributeName.ToLower() == "pr_effectivedate")
                {
                    if (condition.Values.Count > 0 && DateTime.TryParse(condition.Values[0].ToString(), out DateTime queryDate))
                    {
                        localPluginContext.Trace($"Found date filter: {queryDate:yyyy-MM-dd}");
                        return queryDate;
                    }
                }
            }

            // Process child filters recursively
            if (filter.Filters != null)
            {
                foreach (var childFilter in filter.Filters)
                {
                    var result = ExtractDateFromQueryExpression(childFilter, localPluginContext);
                    if (result.HasValue)
                        return result;
                }
            }

            return null;
        }

        private DateTime GetCurrentWeekStart()
        {
            return GetWeekStart(DateTime.Today);
        }

        private DateTime GetWeekStart(DateTime date)
        {
            // Get Monday as start of week
            int diff = (7 + (date.DayOfWeek - DayOfWeek.Monday)) % 7;
            return date.AddDays(-1 * diff).Date;
        }

        private class TimeSlot
        {
            public TimeSpan StartTime { get; set; }
            public TimeSpan EndTime { get; set; }
            public DateTime Date { get; set; }
        }
    }

}

